include:
  # FDK HY0020 (nRF52832), direct SWD image without USB or bootloader.
  - board: hy0020/nrf52832
    shield: hy0020_test
    artifact-name: hy0020_test
  - board: hy0020/nrf52832
    shield: hy0020_test_peripheral
    artifact-name: hy0020_test_peripheral
  - board: hy0020/nrf52832
    shield: settings_reset
    artifact-name: settings_reset-hy0020_nrf52832
