CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_SLEEP=n
CONFIG_LOG=n
CONFIG_SERIAL=n
CONFIG_CONSOLE=n

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Match the proven MDBT50Q dongle radio settings from the reference keyboard.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_CTLR_PHY_2M=n

#CONFIG_BT_MAX_CONN=8
#CONFIG_BT_MAX_PAIRED=8
#CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=n

