CONFIG_ZMK_USB=n
CONFIG_ZMK_BLE=y
#CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_LOG=n
CONFIG_SERIAL=n
CONFIG_CONSOLE=n
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y

#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_BT_CTLR_PHY_2M=n
#CONFIG_ZMK_BLE_THREAD_PRIORITY=3

#CONFIG_ZMK_SLEEP=y
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=2700000